### Question 1: Creating a DataFrame
Create a Pandas DataFrame using a python dictionary with the following columns.  
product  
Region  
Sales  
Quantity  
Add at least 5 rows of sample data and display the DataFrame.

In [ ]:
import pandas as pd
data = {'Product':['Laptop','Tablet', 'Keyboard', 'Monitor', 'Phone'],
        'Region': ['North', 'South', 'East', 'West','South'],
        'Sales': [150, 25, 365, 952, 450],
        'Quantity': [25, 65, 30, 20, 45]}

In [ ]:
data

{'Product': ['Laptop', 'Tablet', 'Keyboard', 'Monitor', 'Phone'],
 'Region': ['North', 'South', 'East', 'West', 'South'],
 'Sales': [150, 25, 365, 952, 450],
 'Quantity': [25, 65, 30, 20, 45]}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

    Product Region  Sales  Quantity
0    Laptop  North    150        25
1    Tablet  South     25        65
2  Keyboard   East    365        30
3   Monitor   West    952        20
4     Phone  South    450        45

In [ ]:
df = pd.read_csv('/content/Retail_dataset.csv')

### Question 2: Data Inspection


1.   Display the first 5 rows of the dataset.
2.   Display the last 5 rows of the dataset.
3.   Show the structure of the dataset using info().
4.   Display the shape of the dataset.

In [ ]:
# 1. Display the first 5 rows of the dataset.
df.head()

   Order_ID Customer   Product Region  Sales  Quantity
0      1001    Sneha    Laptop   West   1056         2
1      1002     Neha    Tablet  South    904         7
2      1003    Meera    Laptop  South   1597         5
3      1004    Rohan  Keyboard  North    777         8
4      1005    Priya     Phone  South   2028         4

In [ ]:
# 2. Display the last 5 rows of the Dataset
df.tail(5)

    Order_ID Customer   Product Region  Sales  Quantity
85      1086    Pooja    Laptop   East   1330         2
86      1087    Anita  Keyboard   West    741         3
87      1088    Karan   Monitor   East    875         2
88      1089      Raj    Tablet  North   2213         5
89      1090    Priya    Laptop  South   1270         2

In [ ]:
# 3. Show the structure of the dataset using info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order_ID  90 non-null     int64
 1   Customer  90 non-null     object
 2   Product   90 non-null     object
 3   Region    90 non-null     object
 4   Sales     90 non-null     int64
 5   Quantity  90 non-null     int64
dtypes: int64(3), object(3)
memory usage: 4.3+ KB

In [ ]:
# 4. Display the shap of the dataset
dataset_Shape = df.shape
print("The shape of the dataset is:", dataset_Shape)

The shape of the dataset is: (90, 6)

### Question 3: Column Selection
Select and display only the following columns:


*   Product
*   Region
*   Sales

In [ ]:
# 1. Select the specific column
selected_columns = df[["Product","Region","Sales"]]

# 2. Display the result
print(selected_columns)

     Product Region  Sales
0     Laptop   West   1056
1     Tablet  South    904
2     Laptop  South   1597
3   Keyboard  North    777
4      Phone  South   2028
..       ...    ...    ...
85    Laptop   East   1330
86  Keyboard   West    741
87   Monitor   East    875
88    Tablet  North   2213
89    Laptop  South   1270

[90 rows x 3 columns]

### Question 4: Indexing using .loc
Using .loc, perform the following:  
1. Display the row with index 10.

2. Display the Sales value of the row with index 20

In [ ]:
# 1. Display the row with index 10.
df.loc[10]

Order_ID       1011
Customer        Raj
Product     Monitor
Region        North
Sales          1693
Quantity          6
Name: 10, dtype: object

In [ ]:
# 2. Display the Sales value of the row with index 20

df.loc[20,'Sales']

np.int64(1021)

Q5. Indexing using .iloc

Using .iloc, display:

1. The first 6 rows and first 4 columns.

2. The Sales value from the 3rd row.

In [ ]:
# 1. The first 6 rows and first 4 columns.
df.iloc[0:6,0:4]

   Order_ID Customer   Product Region
0      1001    Sneha    Laptop   West
1      1002     Neha    Tablet  South
2      1003    Meera    Laptop  South
3      1004    Rohan  Keyboard  North
4      1005    Priya     Phone  South
5      1006    Rahul    Tablet   West

In [ ]:
# 2. The Sales Value from the 3rd row.
sales_value = df.iloc[3,4]
print("Sales value form the 3rd row", sales_value)

Sales value form the 3rd row 777

Q6. Row Slicing

Display:

1. The first 10 rows of the dataset.

2. Rows 15 to 25.

In [ ]:
# 1. The first 10 rows of the dataset.
first_10_rows = df[0:10]
print(first_10_rows)

   Order_ID Customer   Product Region  Sales  Quantity
0      1001    Sneha    Laptop   West   1056         2
1      1002     Neha    Tablet  South    904         7
2      1003    Meera    Laptop  South   1597         5
3      1004    Rohan  Keyboard  North    777         8
4      1005    Priya     Phone  South   2028         4
5      1006    Rahul    Tablet   West    638         2
6      1007     Amit   Monitor  South   1004         7
7      1008    Sneha   Monitor   East   1269         8
8      1009    Priya     Phone  North    827         8
9      1010     Amit     Phone   West   1998         4

In [ ]:
# Rows 15 to 25.
row_15_to_25 = df[15:26]
print(row_15_to_25)

    Order_ID Customer  Product Region  Sales  Quantity
15      1016    Karan  Monitor   West    796         3
16      1017     Neha   Laptop   East   2015         2
17      1018    Anita    Phone  North   1637         3
18      1019     Amit    Phone   East    748         7
19      1020     Neha   Laptop   West   1503         6
20      1021    Priya   Laptop  North   1021         4
21      1022      Raj   Tablet  South    886         7
22      1023    Rahul   Laptop  South   2267         3
23      1024    Karan  Monitor   East    814         7
24      1025    Meera  Monitor   West   1926         6
25      1026    Anita   Tablet   East    839         5

Q7. Filtering Data

Filter the dataset to display:

1. Rows where Region = "East".

2. Rows where Sales > 1500.

In [ ]:
# 1. Rows where Region = "East".
df_East = df[df["Region"] == "East"]
print(df_East)

    Order_ID Customer   Product Region  Sales  Quantity
0       1001    Sneha    Laptop   East   1056         2
1       1002     Neha    Tablet   East    904         7
2       1003    Meera    Laptop   East   1597         5
3       1004    Rohan  Keyboard   East    777         8
4       1005    Priya     Phone   East   2028         4
..       ...      ...       ...    ...    ...       ...
85      1086    Pooja    Laptop   East   1330         2
86      1087    Anita  Keyboard   East    741         3
87      1088    Karan   Monitor   East    875         2
88      1089      Raj    Tablet   East   2213         5
89      1090    Priya    Laptop   East   1270         2

[90 rows x 6 columns]

In [ ]:
# 2. Rows where sales 1500.
sales = df[df["Sales"]> 1500]
print(sales)

    Order_ID Customer   Product Region  Sales  Quantity
2       1003    Meera    Laptop   East   1597         5
4       1005    Priya     Phone   East   2028         4
9       1010     Amit     Phone   East   1998         4
10      1011      Raj   Monitor   East   1693         6
13      1014    Rohan     Phone   East   2078         3
16      1017     Neha    Laptop   East   2015         2
17      1018    Anita     Phone   East   1637         3
19      1020     Neha    Laptop   East   1503         6
22      1023    Rahul    Laptop   East   2267         3
24      1025    Meera   Monitor   East   1926         6
26      1027    Vikas    Laptop   East   1864         8
27      1028    Vikas    Laptop   East   1551         3
29      1030    Rohan   Monitor   East   1932         5
31      1032     Amit    Laptop   East   2226         6
34      1035     Amit    Tablet   East   2104         3
35      1036    Rohan     Phone   East   2136         8
36      1037      Raj     Phone   East   1650         4
37      1038     Amit   Monitor   East   1567         8
38      1039    Meera  Keyboard   East   2455         3
42      1043    Meera  Keyboard   East   1515         6
43      1044    Vikas    Laptop   East   2248         5
44      1045    Priya     Phone   East   1875         4
49      1050    Karan   Monitor   East   2034         7
52      1053    Rahul    Laptop   East   2276         1
57      1058    Meera    Tablet   East   1666         8
58      1059    Karan    Tablet   East   2404         6
59      1060    Karan    Tablet   East   1651         2
60      1061    Vikas   Monitor   East   1837         8
61      1062    Meera  Keyboard   East   1688         4
63      1064    Pooja  Keyboard   East   2310         5
66      1067    Rahul    Tablet   East   1875         6
69      1070    Rahul    Tablet   East   2134         5
71      1072    Anita  Keyboard   East   1702         3
74      1075     Amit   Monitor   East   2390         5
79      1080    Pooja    Tablet   East   1829         2
81      1082    Anita     Phone   East   1695         7
82      1083     Neha  Keyboard   East   2034         5
88      1089      Raj    Tablet   East   2213         5

Q8. Multiple Condition Filtering

Display rows where:

Region is West

Sales is greater than 1200

In [ ]:
filter_df = df[(df["Region"] == "West") & (df["Sales"]>1200)]
print(filter_df)

Empty DataFrame
Columns: [Order_ID, Customer, Product, Region, Sales, Quantity]
Index: []

Q9. Descriptive Statistics

Generate summary statistics using:

describe()

From the result identify:

* Mean sales value

* Maximum quantity sold

* Minimum sales value

In [ ]:
#  Generate summary statistics for the whole dataset
summary_stats = df.describe()
print("--- Summary Statistics ---")
print(summary_stats)

--- Summary Statistics ---
          Order_ID        Sales   Quantity
count    90.000000    90.000000  90.000000
mean   1045.500000  1406.888889   4.700000
std      26.124701   531.748302   2.179836
min    1001.000000   515.000000   1.000000
25%    1023.250000   890.500000   3.000000
50%    1045.500000  1402.000000   5.000000
75%    1067.750000  1857.250000   7.000000
max    1090.000000  2455.000000   8.000000

In [ ]:
# 1 Directly extract and display just the mean sales value
mean_sales = df["Sales"].mean()
mean_sales

np.float64(1406.888888888889)

In [ ]:
# 2. Directly extract and display just the mean sales value
Max_quantity = df["Quantity"].max()
Max_quantity

8

In [ ]:
# 2. Directly extract and display just the mean sales value
min_sales = df["Sales"].min()
min_sales

515

Q10. Aggregation Analysis

Using the Sales column, calculate:

1. Total sales

2. Average sales

3. Maximum sales

4. Minimum sales

In [ ]:
# 1. Total Sales
total_sales = df["Sales"].sum()
print("Total Sales",total_sales)

Total Sales 126620

In [ ]:
# 2. Average Sales
avg_sales = df["Sales"].mean()
print("Average Sales", round(avg_sales,2))

Average Sales 1406.89

In [ ]:
# 3. Maximum Sales
max_sales = df["Sales"].max()
print("Max Sales", max_sales)

Max Sales 2455

In [ ]:
# 4. Min Sales
min_sales = df["Sales"].min()
print("Min Sales", min_sales)

Min Sales 515